services:
  - type: web
    name: miro-workflow-analyzer
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000